--sample data, made up tiers and data, will eventually replace with realworld data--
INSERT INTO champion (champion_name, roletype, tier, winrate) VALUES
    ('Aatrox', 'Top Lane', 'A', 51),
    ('Ahri', 'Mid Lane', 'B', 50),
    ('Akali', 'Top Lane', 'E', 46),
    ('Alistar', 'Support', 'C', 42),
    ('Amumu', 'Tank', 'D', 53),
    ('Anivia', 'Mid Lane', 'S', 50),
    ('Annie', 'Mid Lane', 'S', 60),
    ('Ashe', 'AD Carry', 'A', 45),
    ('Aurelion Sol', 'Support', 'D', 52),
    ('Azir', 'Mid Lane', 'E', 53),
    ('Bard', 'Top Lane', 'B', 49),
    ('Blitzcrank', 'Support', 'S', 51),
    ('Brand', 'Mid Lane', 'A', 54),
    ('Braum', 'Support', 'B', 52),
    ('Caitlyn', 'AD Carry', 'A', 53),
    ('Camille', 'AD Carry', 'C', 50),
    ('Cassiopeia', 'Mid Lane', 'C', 50),
    ('Chogath', 'Top Lane', 'D', 46),
    ('Corki', 'AD Carry', 'A', 50),
    ('Darius', 'Top Lane', 'S', 47),
    ('Diana', 'Mid Lane', 'B', 49),
    ('Dr. Mundo', 'Top', 'D', 50),
    ('Draven', 'AD Carry', 'E', 52),
    ('Ekko', 'Mid Lane', 'B', 50),
    ('Elise', 'Mid Lane', 'A', 50),
    ('Evelynn', 'Jungle', 'S', 54),
    ('Ezreal', 'AD Carry', 'A', 50),
    ('Fiddlesticks', 'Jungle', 'S', 47),
    ('Fiora', 'Top Lane', 'B', 56),
    ('Fizz', 'Mid Lane', 'A', 45),
    ('Galio', 'Mid Lane', 'D', 48),
    ('Gangplank', 'Top Lane', 'E', 52),
    ('Garen', 'Top Lane', 'B', 64),
    ('Gnar', 'Jungle', 'S', 52),
    ('Gragas', 'Mid Lane', 'B', 48),
    ('Graves', 'Jungle', 'S', 55),
    ('Hecarim', 'Jungle', 'A', 60),
    ('Heimerdinger', 'Jungle', 'S', 56),
    ('Illaoi', 'Jungle', 'A', 39),
    ('Irelia', 'Top Lane', 'D', 48),
    ('Ivern', 'Support', 'S', 50),
    ('Janna', 'Support', 'B', 56),
    ('Jarvan IV', 'Jungle', 'S', 48),
    ('Jax', 'Jungle', 'A', 55),
    ('Jhin', 'AD Carry', 'C', 46),
    ('Jinx', 'AD Carry', 'A', 58),
    ('KaiSa', 'Top Lane', 'S', 60),
    ('Kalista', 'Top Lane', 'C', 56),
    ('Karma', 'Support', 'D', 53),
    ('Karthus', 'Mid Lane', 'B', 54),
    ('Kassadin', 'Mid Lane', 'D', 52),
    ('Katarina', 'Mid Lane', 'B', 50),
    ('Kayle', 'Jungle', 'A', 53),
    ('Kayn', 'Jungle', 'C', 46),
    ('Kennen', 'Mid Lane', 'B', 53),
    ('Khazix', 'AD Carry', 'C', 49),
    ('Kindred', 'Jungle', 'A', 56),
    ('Kled', 'Mid Lane', 'B', 48),
    ('KogMaw', 'AD Carry', 'A', 54),
    ('LeBlanc', 'Mid Lane', 'S', 59),
    ('Lee Sin', 'Jungle', 'S', 57),
    ('Leona', 'Support', 'A', 52),
    ('Lissandra', 'Mid Lane', 'C', 51),
    ('Lucian', 'AD Carry', 'B', 50),
    ('Lulu', 'Support', 'C', 49),
    ('Lux', 'Mid Lane', 'A', 53),
    ('Malphite', 'Top', 'B', 49),
    ('Malzahar', 'Mid Lane', 'A', 51),
    ('Maokai', 'Jungle', 'B', 50),
    ('Master Yi', 'Jungle', 'A', 50),
    ('Miss Fortune', 'AD Carry', 'A', 50),
    ('Mordekaiser', 'Top Lane', 'D', 50),
    ('Morgana', 'Mid Lane', 'S', 50),
    ('Nami', 'Support', 'A', 54),
    ('Nasus', 'Top Lane', 'C', 49),
    ('Nautilus', 'Support', 'B', 51),
    ('Nidalee', 'Top Lane', 'C', 45),
    ('Nocturne', 'Jungle', 'A', 53),
    ('Nunu', 'Jungle', 'D', 46),
    ('Olaf', 'Jungle', 'E', 40),
    ('Orianna', 'Mid Lane', 'C', 52),
    ('Ornn', 'Jungle', 'D', 51),
    ('Pantheon', 'Top Lane', 'B', 48),
    ('Poppy', 'Top Lane', 'A', 56),
    ('Pyke', 'Top Lane', 'D', 44),
    ('Quinn', 'AD Carry', 'A', 51),
    ('Rakan', 'Mid Lane', 'B', 49),
    ('Rammus', 'Jungle', 'E', 50),
    ('RekSai', 'Jungle', 'E', 43),
    ('Renekton', 'Top Lane', 'D', 45),
    ('Rengar', 'Jungle', 'A', 52),
    ('Riven', 'Top Lane', 'S', 58),
    ('Rumble', 'Mid Lane', 'A', 55),
    ('Ryze', 'Mid Lane', 'C', 51),
    ('Sejuani', 'Jungle', 'B', 53),
    ('Shaco', 'Jungle', 'C', 47),
    ('Shen', 'Top Lane', 'S', 60),
    ('Shyvana', 'Jungle', 'A', 51),
    ('Singed', 'Top Lane', 'D', 45),
    ('Sion', 'Jungle', 'E', 40),
    ('Sivir', 'AD Carry', 'D', 46),
    ('Skarner', 'Jungle', 'C', 51),
    ('Sona', 'Support', 'A', 55),
    ('Swain', 'Mid Lane', 'B', 50),
    ('Syndra', 'Mid Lane', 'A', 51),
    ('Tahm Kench', 'Jungle', 'C', 49),
    ('Taliyah', 'Mid Lane', 'C', 48),
    ('Talon', 'Jungle', 'E', 47),
    ('Taric', 'Support', 'D', 48),
    ('Teemo', 'Top Lane', 'C', 46),
    ('Thresh', 'Jungle', 'B', 52),
    ('Tristana', 'AD Carry', 'A', 51),
    ('Trundle', 'Jungle', 'B', 56),
    ('Tryndamere', 'Top Lane', 'D', 49),
    ('Twisted Fate', 'Mid Lane', 'C', 51),
    ('Twitch', 'AD Carry', 'B', 58),
    ('Udyr', 'Jungle', 'B', 52),
    ('Urgot', 'AD Carry', 'E', 49),
    ('Varus', 'AD Carry', 'A', 55),
    ('Vayne', 'AD Carry', 'S', 59),
    ('Veigar', 'Mid Lane', 'B', 51),
    ('VelKoz', 'Mid Lane', 'C', 49),
    ('Vi', 'Top Lane', 'A', 52),
    ('Viktor', 'Mid Lane', 'C', 51),
    ('Vladimir', 'Top Lane', 'B', 49),
    ('Volibear', 'Jungle', 'E', 41),
    ('Warwick', 'Jungle', 'D', 46),
    ('Wukong', 'Top Lane', 'B', 51),
    ('Xayah', 'AD Carry', 'C', 49),
    ('Xerath', 'Mid Lane', 'B', 52),
    ('Xin Zhao', 'Jungle', 'C', 51),
    ('Yasuo', 'Top Lane', 'S', 56),
    ('Yorick', 'Top Lane', 'B', 50),
    ('Zac', 'Jungle', 'A', 55),
    ('Zed', 'Mid Lane', 'A', 54),
    ('Ziggs', 'Mid Lane', 'B', 51),
    ('Zilean', 'Mid Lane', 'D', 49),
    ('Zoe', 'Support', 'A', 53),
    ('Zyra', 'Support', 'S', 56)
; -- END CHAMPION INSERTION
