INSERT INTO champion (champion_name, roletype, tier, winrate) VALUES
('Aatrox', 'Top Lane', 'A', 51),
('Ahri', 'Mid Lane', 'B', 50),
('Akali', 'Top Lane', 'E', 46),
('Alistar', 'Support', 'C', 42),
('Amumu', 'Tank', 'D', 53),
('Anivia', 'Mid Lane', 'S', 50),
('Annie', 'Mid Lane', 'S', 60),
('Ashe', 'AD Carry', 'A', 45),
('Aurelion Sol', 'Support', 'D', 52),
('Azir', 'Mid Lane', 'E', 53),
('Bard', 'Top Lane', 'B', 49),
('Blitzcrank', 'Support', 'S', 51),
('Brand', 'Mid Lane', 'A', 54),
('Braum', 'Support', 'B', 52),
('Caitlyn', 'AD Carry', 'A', 53),
('Camille', 'AD Carry', 'C', 50),
('Cassiopeia', 'Mid Lane', 'C', 50),
('Chogath', 'Top Lane', 'D', 46),
('Corki', 'AD Carry', 'A', 50),
('Darius', 'Top Lane', 'S', 47),
('Diana', 'Mid Lane', 'B', 49),
('Dr. Mundo', 'Top', 'D', 50),
('Draven', 'AD Carry', 'E', 52),
('Ekko', 'Mid Lane', 'B', 50),
('Elise', 'Mid Lane', 'A', 50),
('Evelynn', 'Jungle', 'S', 54),
('Ezreal', 'AD Carry', 'A', 50),
('Fiddlesticks', 'Jungle', 'S', 47),
('Fiora', 'Top Lane', 'B', 56),
('Fizz', 'Mid Lane', 'A', 45),
('Galio', 'Mid Lane', 'D', 48),
('Gangplank', 'Top Lane', 'E', 52),
('Garen', 'Top Lane', 'B', 64),
('Gnar', 'Jungle', 'S', 52),
('Gragas', 'Mid Lane', 'B', 48),
('Graves', 'Jungle', 'S', 55),
('Hecarim', 'Jungle', 'A', 60),
('Heimerdinger', 'Jungle', 'S', 56),
('Illaoi', 'Jungle', 'A', 39),
('Irelia', 'Top Lane', 'D', 48),
('Ivern', 'Support', 'S', 50),
('Janna', 'Support', 'B', 56),
('Jarvan IV', 'Jungle', 'S', 48),
('Jax', 'Jungle', 'A', 55),
('Jhin', 'AD Carry', 'C', 46),
('Jinx', 'AD Carry', 'A', 58),
('KaiSa', 'Top Lane', 'S', 60),
('Kalista', 'Top Lane', 'C', 56),
('Karma', 'Support', 'D', 53),
('Karthus', 'Mid Lane', 'B', 54),
('Kassadin', 'Mid Lane', 'D', 52),
('Katarina', 'Mid Lane', 'B', 50),
('Kayle', 'Jungle', 'A', 53),
('Kayn', 'Jungle', 'C', 46),
('Kennen', 'Mid Lane', 'B', 53)

; -- END CHAMPION INSERTION
